apiVersion: koyeb.com/v1alpha1
apps:
  - name: mammamia
    services:
      - name: mammamia
        type: web
        image: github.com/UrloMythus/MammaMia
        regions:
          - fra
        instance_type: eco
        routes:
          - path: /
            port: 8000
        ports:
          - port: 8000
            protocol: http
